services:
    ms-logsmanagement:
        build: .
        restart: always
        ports: 
          - "3030:3000"
        links:
          - mongo
        volumes: 
          - .:/gestion-logs-integracion
        depends_on:
          - mongo
    mongo:
        image: mongo
        restart: always
        command: --serviceExecutor adaptive
        ports: 
          - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
  
    mongo-express:
        image: mongo-express
        restart: always
        links: 
          - mongo
        depends_on:
          - mongo
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example